language: node_js

node_js:
  - "5.0"
  - "6.0"

branches:
  only:
    - master
    - development

env:
  matrix:
  - TEST_TYPE=build
  - TEST_TYPE=test
  - TEST_TYPE=lint
  - TEST_TYPE=flow
  - TEST_TYPE=build_website

script:
  # Check archetype.
  - npm --version
  - npm run start:check
